// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/myproto.proto

/*
Package myproto is a generated protocol buffer package.

It is generated from these files:
	proto/myproto.proto

It has these top-level messages:
	PhoneNumber
	Person
	AddressBook
	AddPersonRequest
	AddPersonResponse
*/
package myproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}
func (PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PhoneNumber struct {
	Number string    `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   PhoneType `protobuf:"varint,2,opt,name=type,enum=myproto.PhoneType" json:"type,omitempty"`
}

func (m *PhoneNumber) Reset()                    { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()               {}
func (*PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

type Person struct {
	Id     int32          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email  string         `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones []*PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type AddressBook struct {
	Person []*Person `protobuf:"bytes,1,rep,name=person" json:"person,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddressBook) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type AddPersonRequest struct {
	Person *Person `protobuf:"bytes,1,opt,name=person" json:"person,omitempty"`
}

func (m *AddPersonRequest) Reset()                    { *m = AddPersonRequest{} }
func (m *AddPersonRequest) String() string            { return proto.CompactTextString(m) }
func (*AddPersonRequest) ProtoMessage()               {}
func (*AddPersonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddPersonRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type AddPersonResponse struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *AddPersonResponse) Reset()                    { *m = AddPersonResponse{} }
func (m *AddPersonResponse) String() string            { return proto.CompactTextString(m) }
func (*AddPersonResponse) ProtoMessage()               {}
func (*AddPersonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddPersonResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*PhoneNumber)(nil), "myproto.PhoneNumber")
	proto.RegisterType((*Person)(nil), "myproto.Person")
	proto.RegisterType((*AddressBook)(nil), "myproto.AddressBook")
	proto.RegisterType((*AddPersonRequest)(nil), "myproto.AddPersonRequest")
	proto.RegisterType((*AddPersonResponse)(nil), "myproto.AddPersonResponse")
	proto.RegisterEnum("myproto.PhoneType", PhoneType_name, PhoneType_value)
}

func init() { proto.RegisterFile("proto/myproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0x36, 0x5d, 0x17, 0xed, 0x0d, 0x66, 0x3d, 0x87, 0xd4, 0x3d, 0x8d, 0x0a, 0x3a, 0x54, 0x26,
	0x4c, 0xf0, 0xc5, 0xa7, 0x0d, 0x06, 0x8a, 0xce, 0x8e, 0x28, 0xfa, 0xbc, 0x91, 0x80, 0x45, 0xdb,
	0xc4, 0xa6, 0x7b, 0xe8, 0xbf, 0x97, 0x5d, 0xbb, 0xea, 0x86, 0xf8, 0x92, 0xdc, 0x7d, 0x5f, 0xbe,
	0xef, 0xbe, 0x0b, 0x1c, 0x9a, 0x4c, 0xe7, 0xfa, 0x2a, 0x29, 0xe8, 0x1e, 0xd0, 0x89, 0xbb, 0x55,
	0x1b, 0x4e, 0xa1, 0x35, 0x7b, 0xd7, 0xa9, 0x7a, 0x5a, 0x26, 0x0b, 0x95, 0xe1, 0x11, 0xf0, 0x94,
	0xaa, 0x80, 0xf5, 0x58, 0xdf, 0x13, 0x55, 0x87, 0xa7, 0xe0, 0xe6, 0x85, 0x51, 0x81, 0xd3, 0x63,
	0xfd, 0xf6, 0x10, 0x07, 0x6b, 0x37, 0xd2, 0xbe, 0x14, 0x46, 0x09, 0xe2, 0x43, 0x03, 0x7c, 0xa6,
	0x32, 0xab, 0x53, 0x6c, 0x83, 0x13, 0x4b, 0x72, 0x69, 0x0a, 0x27, 0x96, 0x88, 0xe0, 0xa6, 0xf3,
	0xa4, 0x74, 0xf0, 0x04, 0xd5, 0xd8, 0x81, 0xa6, 0x4a, 0xe6, 0xf1, 0x67, 0xd0, 0x20, 0xb0, 0x6c,
	0xf0, 0x12, 0xb8, 0x59, 0xd9, 0xda, 0xc0, 0xed, 0x35, 0xfa, 0xad, 0x61, 0x67, 0x73, 0x5a, 0x99,
	0x54, 0x54, 0x6f, 0xc2, 0x1b, 0x68, 0x8d, 0xa4, 0xcc, 0x94, 0xb5, 0x63, 0xad, 0x3f, 0xf0, 0x0c,
	0xb8, 0xa1, 0x00, 0x01, 0x23, 0xf1, 0xfe, 0x8f, 0x98, 0x60, 0x51, 0xd1, 0xe1, 0x2d, 0xf8, 0x23,
	0x29, 0x2b, 0x50, 0x7d, 0x2d, 0x95, 0xcd, 0x37, 0xc4, 0xec, 0x3f, 0xf1, 0x09, 0x1c, 0xfc, 0x12,
	0x5b, 0xa3, 0x53, 0xab, 0xb6, 0x37, 0x3e, 0xbf, 0x00, 0xaf, 0xfe, 0x1e, 0x04, 0xe0, 0xd3, 0x68,
	0x7c, 0xff, 0x38, 0xf1, 0x77, 0x70, 0x0f, 0xdc, 0xbb, 0x68, 0x3a, 0xf1, 0xd9, 0xaa, 0x7a, 0x8b,
	0xc4, 0x83, 0xef, 0x0c, 0x5f, 0x29, 0xce, 0x7a, 0x8d, 0xe7, 0x5c, 0x67, 0x0a, 0xc7, 0xe0, 0xd5,
	0x53, 0xf0, 0xb8, 0xce, 0xb2, 0x1d, 0xbb, 0xdb, 0xfd, 0x8b, 0x2a, 0x43, 0x2d, 0x38, 0x11, 0xd7,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xad, 0xf0, 0x70, 0x06, 0x02, 0x00, 0x00,
}
